blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/wagmi-dev/wagmi/discussions/new?category=q-a
    about: Ask questions and discuss with other community members.
  - name: Feature Request
    url: https://github.com/wagmi-dev/wagmi/discussions/new?category=ideas
    about: Requests features or brainstorm ideas for new functionality.
