name: Issue Labeled

on:
  issues:
    types: [labeled]

jobs:
  issue-labeled:
    if: ${{ github.repository_owner == 'wevm' }}
    uses: wevm/actions/.github/workflows/issue-labeled.yml@main
    with:
      needs-reproduction-body: |
        Hello @${{ github.event.issue.user.login }}. 

        Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) using [StackBlitz](https://new.wagmi.sh), [TypeScript Playground](https://www.typescriptlang.org/play) (for type issues), or a separate minimal GitHub repository.

        [Minimal reproductions are required](https://antfu.me/posts/why-reproductions-are-required) as they save us a lot of time reproducing your config/environment and issue, and allow us to help you faster.

        Once a minimal reproduction is added, a team member will confirm it works, then re-open the issue.
