name: vhs

on:
  push:
    paths:
      - packages/**/*.tape
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  VHS: true

jobs:
  vhs:
    name: vhs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        pnpm-version: [7.19]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}

      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            docs/node_modules
            examples/**/node_modules
            packages/**/node_modules
            references/packages/**/node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install Dependencies
        run: pnpm i

      # TODO: Combine these steps once supported
      # https://github.com/charmbracelet/vhs-action/issues/50
      - uses: charmbracelet/vhs-action@v1
        with:
          path: 'packages/cli/vhs/init.tape'
      - uses: charmbracelet/vhs-action@v1
        with:
          path: 'packages/cli/vhs/generate.tape'
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'chore: update vhs'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          file_pattern: '*.gif *.mp4'
